; generated by Component: ARM Compiler 5.06 update 6 (build 750) Tool: ArmCC [4d3637]
; commandline ArmCC [--c99 --split_sections --debug -c -S -o..\6bin\cmd_fun.s --depend=..\6bin\cmd_fun.d --cpu=Cortex-M4.fp --apcs=interwork --diag_suppress=9931 -I..\1McuLayer\CMSIS -I..\1McuLayer\STM32F4xx_StdPeriph_Driver\inc -I..\2LowLayer\LED -I..\3MiddleLayer\delay -I..\3MiddleLayer\sys -I..\2LowLayer\USART -I..\4UserLayer -I..\5FreeRTOS\include -I..\5FreeRTOS\portable\RVDS\ARM_CM4F -I..\2LowLayer\FLASH -I..\2LowLayer\KEY -I..\3MiddleLayer\easyflash\inc -I..\2LowLayer\TIME -I..\2LowLayer\FLASH\inc -I..\3MiddleLayer\ini -I..\3MiddleLayer\stmflash -I..\3MiddleLayer\ymodem -I..\3MiddleLayer\cjson -I..\3MiddleLayer\malloc -I..\2LowLayer\BEEP -I..\2LowLayer\INFRARED -I.\RTE\_SMCS_BASE_APP -Id:\Keil_v5\Packs\Keil\STM32F4xx_DFP\2.13.0\Drivers\CMSIS\Device\ST\STM32F4xx\Include -Id:\Keil_v5\ARM\CMSIS\Include -D__UVISION_VERSION=527 -DSTM32F407xx -DSTM32F40_41xxx -DUSE_STDPERIPH_DRIVER --omf_browse=..\6bin\cmd_fun.crf ..\5FreeRTOS\cli\cmd_fun.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.CMD_Init||, CODE, READONLY, ALIGN=2

CMD_Init PROC
        PUSH     {r4-r6,lr}
        MOVS     r5,#9
        LDR      r6,|L0.24|
        MOVS     r4,#0
|L0.8|
        ADD      r0,r6,r4,LSL #4
        BL       FreeRTOS_CLIRegisterCommand
        ADDS     r4,r4,#1
        CMP      r4,r5
        BCC      |L0.8|
        POP      {r4-r6,pc}
        ENDP

|L0.24|
        DCD      ||.constdata||

        AREA ||i.prvDelEnv||, CODE, READONLY, ALIGN=2

prvDelEnv PROC
        PUSH     {r3-r7,lr}
        MOV      r3,r2
        MOV      r6,r1
        MOVS     r5,r0
        BEQ      |L1.72|
        MOV      r2,sp
        MOVS     r1,#1
        MOV      r0,r3
        BL       FreeRTOS_CLIGetParameter
        MOVS     r4,r0
        BEQ      |L1.88|
        MOV      r1,r6
        MOV      r0,r5
        BL       __aeabi_memclr
        ADR      r1,|L1.116|
        MOV      r0,r5
        BL       __2sprintf
        MOV      r1,r4
        MOV      r0,r5
        LDR      r2,[sp,#0]
        BL       strncat
        MOVS     r2,#2
        ADR      r1,|L1.148|
        MOV      r0,r5
        BL       strncat
        MOV      r0,r4
        BL       ef_del_env
        CBZ      r0,|L1.104|
        ADR      r1,|L1.152|
        B        |L1.106|
|L1.72|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L1.86|
        B        |L1.86|
|L1.88|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L1.102|
        B        |L1.102|
|L1.104|
        ADR      r1,|L1.168|
|L1.106|
        MOV      r0,r5
        BL       strcat
        MOVS     r0,#0
        POP      {r3-r7,pc}
        ENDP

|L1.116|
        DCB      "The key value to be deleted is:",0
|L1.148|
        DCB      "\r\n",0
        DCB      0
|L1.152|
        DCB      "delenv error \r\n",0
|L1.168|
        DCB      "The key has been deleted\r\n",0
        DCB      0

        AREA ||i.prvGetEnv||, CODE, READONLY, ALIGN=2

prvGetEnv PROC
        PUSH     {r3-r7,lr}
        MOV      r3,r2
        MOV      r6,r1
        MOVS     r5,r0
        BEQ      |L2.108|
        MOV      r2,sp
        MOVS     r1,#1
        MOV      r0,r3
        BL       FreeRTOS_CLIGetParameter
        MOVS     r4,r0
        BEQ      |L2.124|
        MOV      r1,r6
        MOV      r0,r5
        BL       __aeabi_memclr
        ADR      r1,|L2.152|
        MOV      r0,r5
        BL       __2sprintf
        MOV      r1,r4
        MOV      r0,r5
        LDR      r2,[sp,#0]
        BL       strncat
        MOVS     r2,#2
        ADR      r1,|L2.168|
        MOV      r0,r5
        BL       strncat
        MOV      r0,r4
        BL       ef_get_env
        MOVS     r4,r0
        BEQ      |L2.140|
        ADR      r1,|L2.172|
        MOV      r0,r5
        BL       strcat
        MOV      r0,r4
        BL       strlen
        MOV      r2,r0
        MOV      r1,r4
        MOV      r0,r5
        BL       strncat
        MOVS     r2,#2
        ADR      r1,|L2.168|
        MOV      r0,r5
        BL       strncat
|L2.104|
        MOVS     r0,#0
        POP      {r3-r7,pc}
|L2.108|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L2.122|
        B        |L2.122|
|L2.124|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L2.138|
        B        |L2.138|
|L2.140|
        ADR      r1,|L2.188|
        MOV      r0,r5
        BL       strcat
        B        |L2.104|
        ENDP

        DCW      0x0000
|L2.152|
        DCB      "the key is :",0
        DCB      0
        DCB      0
        DCB      0
|L2.168|
        DCB      "\r\n",0
        DCB      0
|L2.172|
        DCB      "the value is :",0
        DCB      0
|L2.188|
        DCB      "getenv error \r\n",0

        AREA ||i.prvParameterEchoCommand||, CODE, READONLY, ALIGN=2

        REQUIRE _printf_percent
        REQUIRE _printf_d
        REQUIRE _printf_int_dec
prvParameterEchoCommand PROC
        PUSH     {r3-r7,lr}
        MOV      r3,r2
        MOV      r7,r1
        MOVS     r5,r0
        BEQ      |L3.74|
        LDR      r6,|L3.112|
        LDR      r1,[r6,#4]  ; uxParameterNumber
        CBZ      r1,|L3.90|
        MOV      r2,sp
        MOV      r0,r3
        BL       FreeRTOS_CLIGetParameter
        MOVS     r4,r0
        BEQ      |L3.102|
        MOV      r1,r7
        MOV      r0,r5
        BL       __aeabi_memclr
        ADR      r1,|L3.116|
        MOV      r0,r5
        LDR      r2,[r6,#4]  ; uxParameterNumber
        BL       __2sprintf
        MOV      r1,r4
        MOV      r0,r5
        LDR      r2,[sp,#0]
        BL       strncat
        MOVS     r2,#2
        ADR      r1,|L3.124|
        MOV      r0,r5
        BL       strncat
        LDR      r1,[r6,#4]  ; uxParameterNumber
        MOVS     r0,#1
        ADDS     r1,r1,#1
        B        |L3.108|
|L3.74|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L3.88|
        B        |L3.88|
|L3.90|
        ADR      r1,|L3.128|
        BL       __2sprintf
        MOVS     r0,#1
        STR      r0,[r6,#4]  ; uxParameterNumber
        POP      {r3-r7,pc}
|L3.102|
        MOVS     r1,#0
        STRB     r1,[r5,#0]
        MOV      r0,r1
|L3.108|
        STR      r1,[r6,#4]  ; uxParameterNumber
        POP      {r3-r7,pc}
        ENDP

|L3.112|
        DCD      ||.data||
|L3.116|
        DCB      "%d: ",0
        DCB      0
        DCB      0
        DCB      0
|L3.124|
        DCB      "\r\n",0
        DCB      0
|L3.128|
        DCB      "The parameters were:\r\n",0
        DCB      0

        AREA ||i.prvPrintEnv||, CODE, READONLY, ALIGN=2

prvPrintEnv PROC
        PUSH     {r4,lr}
        MOVS     r4,r0
        BEQ      |L4.22|
        BL       ef_print_env
        ADR      r1,|L4.40|
        MOV      r0,r4
        BL       __2sprintf
        MOVS     r0,#0
        POP      {r4,pc}
|L4.22|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L4.36|
        B        |L4.36|
        ENDP

        DCW      0x0000
|L4.40|
        DCB      "Display parameters list\r\n",0
        DCB      0
        DCB      0

        AREA ||i.prvResetEnv||, CODE, READONLY, ALIGN=2

prvResetEnv PROC
        PUSH     {r4,lr}
        MOVS     r4,r0
        BEQ      |L5.16|
        BL       ef_env_set_default
        CBZ      r0,|L5.32|
        ADR      r1,|L5.44|
        B        |L5.34|
|L5.16|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L5.30|
        B        |L5.30|
|L5.32|
        ADR      r1,|L5.72|
|L5.34|
        MOV      r0,r4
        BL       strcat
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP

|L5.44|
        DCB      "ef_env_set_default error \r\n",0
|L5.72|
        DCB      "Restore default Settings Success\r\n",0
        DCB      0

        AREA ||i.prvRunTimeStatsCommand||, CODE, READONLY, ALIGN=2

prvRunTimeStatsCommand PROC
        PUSH     {r4-r6,lr}
        LDR      r5,|L6.80|
        MOVS     r4,r0
        BEQ      |L6.64|
        ADR      r1,|L6.84|
        BL       strcpy
        MOV      r0,r4
        BL       strlen
        ADD      r4,r4,r0
        MOVS     r0,#4
        MOVS     r2,#0
        MOVS     r1,#0x20
|L6.28|
        STRB     r1,[r4],#1
        ADDS     r0,r0,#1
        STRB     r2,[r4,#0]
        CMP      r0,#7
        BLT      |L6.28|
        MOV      r1,r5
        MOV      r0,r4
        BL       strcpy
        MOV      r0,r5
        BL       strlen
        ADD      r0,r0,r4
        BL       vTaskGetRunTimeStats
        MOVS     r0,#0
        POP      {r4-r6,pc}
|L6.64|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L6.78|
        B        |L6.78|
        ENDP

|L6.80|
        DCD      ||.conststring||+0x2ec
|L6.84|
        DCB      "Task",0
        DCB      0
        DCB      0
        DCB      0

        AREA ||i.prvSetEnv||, CODE, READONLY, ALIGN=2

prvSetEnv PROC
        PUSH     {r2-r8,lr}
        MOV      r4,r2
        MOV      r7,r1
        MOVS     r6,r0
        BEQ      |L7.132|
        MOV      r2,sp
        MOVS     r1,#1
        MOV      r0,r4
        BL       FreeRTOS_CLIGetParameter
        MOV      r5,r0
        ADD      r2,sp,#4
        MOVS     r1,#2
        MOV      r0,r4
        BL       FreeRTOS_CLIGetParameter
        MOV      r4,r0
        CMP      r5,#0
        BEQ      |L7.148|
        CMP      r4,#0
        BEQ      |L7.164|
        LDR      r1,[sp,#0]
        MOVS     r0,#0
        STRB     r0,[r5,r1]
        LDR      r1,[sp,#4]
        STRB     r0,[r4,r1]
        MOV      r1,r7
        MOV      r0,r6
        BL       __aeabi_memclr
        ADR      r1,|L7.196|
        MOV      r0,r6
        BL       __2sprintf
        MOV      r1,r5
        MOV      r0,r6
        LDR      r2,[sp,#0]
        BL       strncat
        MOVS     r2,#2
        ADR      r1,|L7.212|
        MOV      r0,r6
        BL       strncat
        ADR      r1,|L7.216|
        MOV      r0,r6
        BL       strcat
        MOV      r1,r4
        MOV      r0,r6
        LDR      r2,[sp,#4]
        BL       strncat
        MOVS     r2,#2
        ADR      r1,|L7.212|
        MOV      r0,r6
        BL       strncat
        MOV      r1,r4
        MOV      r0,r5
        BL       ef_set_env
        CBZ      r0,|L7.180|
        ADR      r1,|L7.232|
        B        |L7.182|
|L7.132|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L7.146|
        B        |L7.146|
|L7.148|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L7.162|
        B        |L7.162|
|L7.164|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L7.178|
        B        |L7.178|
|L7.180|
        ADR      r1,|L7.248|
|L7.182|
        MOV      r0,r6
        BL       strcat
        MOVS     r0,#0
        POP      {r2-r8,pc}
        ENDP

        DCW      0x0000
|L7.196|
        DCB      "The key is :",0
        DCB      0
        DCB      0
        DCB      0
|L7.212|
        DCB      "\r\n",0
        DCB      0
|L7.216|
        DCB      "The value is :",0
        DCB      0
|L7.232|
        DCB      "setenv error \r\n",0
|L7.248|
        DCB      "setenv success \r\n",0
        DCB      0
        DCB      0

        AREA ||i.prvTaskStatsCommand||, CODE, READONLY, ALIGN=2

prvTaskStatsCommand PROC
        PUSH     {r4-r6,lr}
        LDR      r5,|L8.80|
        MOVS     r4,r0
        BEQ      |L8.64|
        ADR      r1,|L8.84|
        BL       strcpy
        MOV      r0,r4
        BL       strlen
        ADD      r4,r4,r0
        MOVS     r0,#4
        MOVS     r2,#0
        MOVS     r1,#0x20
|L8.28|
        STRB     r1,[r4],#1
        ADDS     r0,r0,#1
        STRB     r2,[r4,#0]
        CMP      r0,#7
        BLT      |L8.28|
        MOV      r1,r5
        MOV      r0,r4
        BL       strcpy
        MOV      r0,r5
        BL       strlen
        ADD      r0,r0,r4
        BL       vTaskList
        MOVS     r0,#0
        POP      {r4-r6,pc}
|L8.64|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L8.78|
        B        |L8.78|
        ENDP

|L8.80|
        DCD      ||.conststring||+0x294
|L8.84|
        DCB      "Task",0
        DCB      0
        DCB      0
        DCB      0

        AREA ||i.prvThreeParameterEchoCommand||, CODE, READONLY, ALIGN=2

        REQUIRE _printf_percent
        REQUIRE _printf_d
        REQUIRE _printf_int_dec
prvThreeParameterEchoCommand PROC
        PUSH     {r3-r7,lr}
        MOV      r3,r2
        MOV      r7,r1
        MOVS     r6,r0
        BEQ      |L9.80|
        LDR      r5,|L9.132|
        LDR      r1,[r5,#0]  ; uxParameterNumber
        CBZ      r1,|L9.96|
        MOV      r2,sp
        MOV      r0,r3
        BL       FreeRTOS_CLIGetParameter
        MOVS     r4,r0
        BEQ      |L9.108|
        MOV      r1,r7
        MOV      r0,r6
        BL       __aeabi_memclr
        ADR      r1,|L9.136|
        MOV      r0,r6
        LDR      r2,[r5,#0]  ; uxParameterNumber
        BL       __2sprintf
        MOV      r1,r4
        MOV      r0,r6
        LDR      r2,[sp,#0]
        BL       strncat
        MOVS     r2,#2
        ADR      r1,|L9.144|
        MOV      r0,r6
        BL       strncat
        LDR      r1,[r5,#0]  ; uxParameterNumber
        CMP      r1,#3
        BEQ      |L9.124|
        MOVS     r0,#1
        ADDS     r1,r1,#1
|L9.76|
        STR      r1,[r5,#0]  ; uxParameterNumber
        POP      {r3-r7,pc}
|L9.80|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L9.94|
        B        |L9.94|
|L9.96|
        ADR      r1,|L9.148|
        BL       __2sprintf
        MOVS     r0,#1
        STR      r0,[r5,#0]  ; uxParameterNumber
        POP      {r3-r7,pc}
|L9.108|
        MOVS     r0,#0x50
        MSR      BASEPRI,r0
        DSB      
        ISB      
|L9.122|
        B        |L9.122|
|L9.124|
        MOVS     r0,#0
        MOV      r1,r0
        B        |L9.76|
        ENDP

        DCW      0x0000
|L9.132|
        DCD      ||.data||
|L9.136|
        DCB      "%d: ",0
        DCB      0
        DCB      0
        DCB      0
|L9.144|
        DCB      "\r\n",0
        DCB      0
|L9.148|
        DCB      "The three parameters were:\r\n",0
        DCB      0
        DCB      0
        DCB      0

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.constdata||, DATA, READONLY, ALIGN=2

CLI_Definition_All
        DCD      ||.conststring||
        DCD      ||.conststring||+0xc
        DCD      prvTaskStatsCommand
        DCB      0x00,0x00,0x00,0x00
        DCD      ||.conststring||+0x58
        DCD      ||.conststring||+0x6c
        DCD      prvThreeParameterEchoCommand
        DCB      0x03,0x00,0x00,0x00
        DCD      ||.conststring||+0xc0
        DCD      ||.conststring||+0xd0
        DCD      prvParameterEchoCommand
        DCB      0xff,0x00,0x00,0x00
        DCD      ||.conststring||+0x124
        DCD      ||.conststring||+0x134
        DCD      prvRunTimeStatsCommand
        DCB      0x00,0x00,0x00,0x00
        DCD      ||.conststring||+0x198
        DCD      ||.conststring||+0x1a4
        DCD      prvPrintEnv
        DCB      0x00,0x00,0x00,0x00
        DCD      ||.conststring||+0x1d0
        DCD      ||.conststring||+0x1d8
        DCD      prvSetEnv
        DCB      0x02,0x00,0x00,0x00
        DCD      ||.conststring||+0x200
        DCD      ||.conststring||+0x208
        DCD      prvGetEnv
        DCB      0x01,0x00,0x00,0x00
        DCD      ||.conststring||+0x230
        DCD      ||.conststring||+0x238
        DCD      prvDelEnv
        DCB      0x01,0x00,0x00,0x00
        DCD      ||.conststring||+0x25c
        DCD      ||.conststring||+0x268
        DCD      prvResetEnv
        DCB      0x00,0x00,0x00,0x00

        AREA ||.conststring||, DATA, READONLY, MERGE=1, STRINGS, ALIGN=2

        DCB      "tasklist",0
        DCB      0
        DCB      0
        DCB      0
        DCB      "\r\ntasklist:\r\n Displays a table showing the state of"
        DCB      " each FreeRTOS task\r\n",0
        DCB      0
        DCB      0
        DCB      0
        DCB      "echo-3-parameters",0
        DCB      0
        DCB      0
        DCB      "\r\necho <param1> <param2> <param3>:\r\n Expects three "
        DCB      "parameters, echos each in turn\r\n",0
        DCB      "echo-parameters",0
        DCB      "\r\necho-parameters <...>:\r\n Take variable number of "
        DCB      "parameters, echos each in turn\r\n",0
        DCB      "run-time-stats",0
        DCB      0
        DCB      "\r\nrun-time-stats:\r\n Displays a table showing how mu"
        DCB      "ch processing time each FreeRTOS task has used\r\n",0
        DCB      "printenv",0
        DCB      0
        DCB      0
        DCB      0
        DCB      "\r\nprintenv:\r\n Display all parameters\r\n\r\n",0
        DCB      0
        DCB      0
        DCB      0
        DCB      "setenv",0
        DCB      0
        DCB      "\r\nsetenv:\r\n set the value of key \r\n\r\n",0
        DCB      0
        DCB      0
        DCB      "getenv",0
        DCB      0
        DCB      "\r\ngetenv:\r\n set the value of key \r\n\r\n",0
        DCB      0
        DCB      0
        DCB      "delenv",0
        DCB      0
        DCB      "\r\ndelenv:\r\n del the key value \r\n\r\n",0
        DCB      0
        DCB      "resetenv",0
        DCB      0
        DCB      0
        DCB      0
        DCB      "\r\nresetenv:\r\n Restore default Settings \r\n\r\n",0
        DCB      "     State   Priority  Stack    #\r\n******************"
        DCB      "******************************\r\n",0
        DCB      0
        DCB      0
        DCB      "  Abs Time      % Time\r\n*****************************"
        DCB      "***********\r\n",0

        AREA ||.data||, DATA, ALIGN=2

uxParameterNumber
        DCD      0x00000000
|symbol_number.17|
        DCD      0x00000000

        EXPORT CMD_Init [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT FreeRTOS_CLIRegisterCommand [CODE]
        IMPORT strcpy [CODE]
        IMPORT strlen [CODE]
        IMPORT vTaskList [CODE]
        IMPORT vTaskGetRunTimeStats [CODE]
        IMPORT __2sprintf [CODE]
        IMPORT FreeRTOS_CLIGetParameter [CODE]
        IMPORT __aeabi_memclr [CODE]
        IMPORT _printf_percent [CODE]
        IMPORT _printf_d [CODE]
        IMPORT _printf_int_dec [CODE]
        IMPORT strncat [CODE]
        IMPORT ef_print_env [CODE]
        IMPORT ef_get_env [CODE]
        IMPORT strcat [CODE]
        IMPORT ef_set_env [CODE]
        IMPORT ef_del_env [CODE]
        IMPORT ef_env_set_default [CODE]

        KEEP prvDelEnv
        KEEP prvGetEnv
        KEEP prvParameterEchoCommand
        KEEP prvPrintEnv
        KEEP prvResetEnv
        KEEP prvRunTimeStatsCommand
        KEEP prvSetEnv
        KEEP prvTaskStatsCommand
        KEEP prvThreeParameterEchoCommand
        KEEP CLI_Definition_All
        KEEP uxParameterNumber
        KEEP |symbol_number.17|
        EXPORTAS |symbol_number.17|, uxParameterNumber

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
